in:
  type: pcapng_files
  paths: [ . ]
  convertdot: "-"
  threads: 1
  schema:
    - { name: frame.time_epoch, type: timestamp }
    - { name: frame.number, type: long }
    - { name: wlan.ta, type: string }
    - { name: wlan.ra, type: string }
    - { name: radiotap.datarate, type: long }
